name: Feature Request
description: Suggest a feature for this library.
labels: [enhancement]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the feature.
    validations:
      required: true
